### PR TITLE
Detect screenshare rotation

### PR DESCRIPTION
**Pull request by davidliu**

### CODE REVIEW

**Comment by bennnjamin** [comment]
These changes look very similar to what is required to fix this issue #535. Especially since it's possible for the device to be in landscape while screensharing when switching between apps. I would greatly appreciate if you took another look at a robust orientation handling solution for the camera in addition to screensharing.

**Comment by davidliu** [comment]
@bennnjamin As I noted in #535, the camera is already following the rotation of the device's UI, so I'm not sure what's actionable there.

**Comment by bennnjamin** [comment]
@davidliu it doesn't follow the device's UI when switching apps or when there is no foreground activity. It's certainly jarring to a subscriber to see the camera swapping between landscape and portrait orientation during normal operation of the phone. The expectation from a UX perspective is that the video orientation matches the device even when switching apps or multitasking.

The action is to use ```OrientationListener``` instead of ```WindowManager``` for camera video track orientation like in this pull request but even better would be to allow the developer override the frame orientation. Then it's up to them if they would like to override the default behavior with a custom `OrientationListener`.

**Comment by davidliu** [comment]
@bennnjamin that's possible to do with a VideoProcessor, though you shouldn't have to. If you can provide a repro example, I'll gladly recheck it and provide a fix if needed, but it was working fine for me.

**Comment by bennnjamin** [comment]
@davidliu I appreciate your willingness to help with this. Perhaps I was looking in the wrong place to override rotation. Can you link to a method that is overridable? Here is are the methods I found for frame rotation but they are all private.

https://github.com/livekit/client-sdk-android/blob/dcbb36b25a318c53c5d15a27f4e83fd8e73b2da3/livekit-android-camerax/src/main/java/livekit/org/webrtc/CameraXSession.kt#L305

And in WebRTC:

https://github.com/webrtc-sdk/webrtc/blob/b99fd2c270361aea2d458e61ac4a4cd2443bdbf6/sdk/android/src/java/org/webrtc/Camera2Session.java#L413


https://github.com/webrtc-sdk/webrtc/blob/b99fd2c270361aea2d458e61ac4a4cd2443bdbf6/sdk/android/src/java/org/webrtc/CameraSession.java#L42

**Comment by bennnjamin** [comment]
@davidliu kindly checking to see if you are able to provide further guidance on the correct place to override frame rotation for `Camera2` and `Camerax` sessions

**Pull request merged**
