### PR TITLE
android higher level track apis

### PR DESCRIPTION
**Pull request by davidliu**

### CODE REVIEW

**Review by hiroshihorie — APPROVED** [review]
✅

**Comment by davidzhao** [comment]
what ends up calling `setTrackEnabled` ? Could you update the README docs as well?

**Comment by davidliu** [comment]
Agh, forgot to include the direct calls for the camera/mic. good catch. will update.

**Comment by davidzhao** [comment]
it'd be great to update the sample app to use them as well.

**Comment by derek-m-ir** [comment]
No longer able to mute/unmute LocalTrackPublication.  The mute property is read-only

**Pull request merged**
